name: Cask CI

on:
  pull_request:
    paths:
      - 'Casks/**'

permissions: {}

jobs:
  casks:
    permissions:
      contents: read
    uses: meigma/release/.github/workflows/homebrew-tap-ci.yml@6a56ff6798d77143d21156f1227e55409401535e
